"""initial_schema

Revision ID: 417420701000
Revises: 
Create Date: 2026-07-17 07:19:13.391774

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '417420701000'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('root_path', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('scanners', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('engine_versions', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'seq', name='uq_scans_project_seq')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_project_id'), ['project_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=16), nullable=False),
    sa.Column('source_scanner', sa.String(length=8), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=True),
    sa.Column('usage_context', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=12), nullable=False),
    sa.Column('shelf_life_years', sa.Float(), nullable=True),
    sa.Column('qv_vulnerable', sa.Boolean(), nullable=False),
    sa.Column('qv_attack', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('protocol_detail', sa.JSON(), nullable=True),
    sa.Column('library', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_ci_low', sa.Float(), nullable=True),
    sa.Column('risk_ci_high', sa.Float(), nullable=True),
    sa.Column('mosca_margin_years', sa.Float(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('migration_status', sa.String(length=10), nullable=True),
    sa.Column('migration_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_algorithm'), ['algorithm'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_assets_proj_fp', ['project_id', 'fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_assets_qv_vulnerable'), ['qv_vulnerable'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_assets_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index('ix_assets_scan_algo', ['scan_id', 'algorithm'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_scan_id'), ['scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_scan_id'))
        batch_op.drop_index('ix_assets_scan_algo')
        batch_op.drop_index(batch_op.f('ix_assets_risk_score'))
        batch_op.drop_index(batch_op.f('ix_assets_qv_vulnerable'))
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))
        batch_op.drop_index('ix_assets_proj_fp')
        batch_op.drop_index(batch_op.f('ix_assets_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_assets_algorithm'))

    op.drop_table('assets')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_project_id'))

    op.drop_table('scans')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    # ### end Alembic commands ###
