"""migrate_001_migration_tables

Revision ID: fd0d98569dd7
Revises: efae907d39c1
Create Date: 2026-07-18 00:15:54.699782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0d98569dd7'
down_revision: Union[str, Sequence[str], None] = 'efae907d39c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migration_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('member_ids_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_units_plan_id'), ['plan_id'], unique=False)

    op.create_table('migration_dependency_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('src_asset_id', sa.Uuid(), nullable=False),
    sa.Column('dst_asset_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dst_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_dependency_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_dependency_edges_plan_id'), ['plan_id'], unique=False)

    op.create_table('migration_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('effort_points', sa.Integer(), nullable=False),
    sa.Column('effort_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['migration_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_tasks_plan_id'), ['plan_id'], unique=False)

    op.create_table('migration_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['migration_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_events_task_id'), ['task_id'], unique=False)

    op.create_table('migration_patches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('generator', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('base_sha256', sa.String(length=64), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('new_files_json', sa.JSON(), nullable=False),
    sa.Column('validation_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_branch', sa.String(length=128), nullable=True),
    sa.Column('applied_commit', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['migration_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_patches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_patches_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('migration_patches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_patches_task_id'))

    op.drop_table('migration_patches')
    with op.batch_alter_table('migration_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_events_task_id'))

    op.drop_table('migration_events')
    with op.batch_alter_table('migration_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_tasks_plan_id'))

    op.drop_table('migration_tasks')
    with op.batch_alter_table('migration_dependency_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_dependency_edges_plan_id'))

    op.drop_table('migration_dependency_edges')
    with op.batch_alter_table('migration_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_units_plan_id'))

    op.drop_table('migration_units')
    op.drop_table('migration_plans')
    # ### end Alembic commands ###
