/**
 * Renders a QUBIT remediation plan.
 *
 * Not a general markdown renderer, deliberately. The text this displays is generated by QUBIT's
 * own `GuidedPlan.to_markdown()`, so its shapes are a closed set — an h2 headline, a `**Target:**`
 * line, a blockquote for the honest note, a numbered step list with bold titles and fenced
 * commands, and a `### Sources` list. Rendering exactly those is a few dozen lines, has no
 * dependency, and cannot emit HTML from text it was given. Pulling in a markdown parser to read
 * our own format would be more surface for less certainty.
 *
 * The one part that is NOT ours is the section the local model writes after the `---` separator.
 * That falls through to preformatted text, which is the honest treatment for prose from a model:
 * shown as written, never interpreted.
 */
import { Fragment } from 'react';

/** Bold spans (`**x**`) and inline code (`` `x` ``) inside one line of plan text. */
function inline(text: string, keyPrefix: string) {
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean);
  return parts.map((part, i) => {
    const key = `${keyPrefix}-${i}`;
    if (part.startsWith('**') && part.endsWith('**')) {
      return (
        <strong key={key} className="font-semibold text-[color:var(--color-ink)]">
          {part.slice(2, -2)}
        </strong>
      );
    }
    if (part.startsWith('`') && part.endsWith('`')) {
      return (
        <code key={key} className="rounded bg-black/40 px-1 py-0.5 font-mono text-[0.95em]">
          {part.slice(1, -1)}
        </code>
      );
    }
    return <Fragment key={key}>{part}</Fragment>;
  });
}

type Block =
  | { kind: 'h2' | 'h3' | 'para' | 'quote' | 'bullet' | 'step'; text: string }
  | { kind: 'code'; text: string };

/** Split the plan into the blocks this component knows how to draw. */
function parse(markdown: string): Block[] {
  const blocks: Block[] = [];
  const lines = markdown.split('\n');
  let code: string[] | null = null;

  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '');
    const trimmed = line.trim();

    if (trimmed === '```') {
      if (code) {
        blocks.push({ kind: 'code', text: code.join('\n') });
        code = null;
      } else {
        code = [];
      }
      continue;
    }
    if (code) {
      // Steps indent their fenced blocks by three spaces; strip that, keep deeper indentation.
      code.push(line.replace(/^ {3}/, ''));
      continue;
    }
    if (!trimmed) continue;

    if (trimmed.startsWith('## ')) blocks.push({ kind: 'h2', text: trimmed.slice(3) });
    else if (trimmed.startsWith('### ')) blocks.push({ kind: 'h3', text: trimmed.slice(4) });
    else if (trimmed.startsWith('> ')) blocks.push({ kind: 'quote', text: trimmed.slice(2) });
    else if (/^\d+\.\s/.test(trimmed))
      blocks.push({ kind: 'step', text: trimmed.replace(/^\d+\.\s*/, '') });
    else if (trimmed.startsWith('- ')) blocks.push({ kind: 'bullet', text: trimmed.slice(2) });
    else {
      // A continuation line under a step, or an ordinary paragraph. Both read as body text.
      const previous = blocks[blocks.length - 1];
      if (previous && (previous.kind === 'step' || previous.kind === 'para') && line.startsWith(' ')) {
        previous.text = `${previous.text} ${trimmed}`;
      } else {
        blocks.push({ kind: 'para', text: trimmed });
      }
    }
  }
  if (code) blocks.push({ kind: 'code', text: code.join('\n') });
  return blocks;
}

export function GuidancePanel({ text }: { text: string }) {
  // Everything after the separator is the model's reading of the file, not QUBIT's plan.
  const split = text.indexOf('\n---\n');
  const plan = split >= 0 ? text.slice(0, split) : text;
  const modelSection = split >= 0 ? text.slice(split + 5) : '';
  const blocks = parse(plan);
  let stepNumber = 0;

  return (
    <div className="rounded-[3px] border border-[color:var(--edge)] bg-black/30 p-4 text-xs leading-relaxed text-[color:var(--color-ink-dim)]">
      {blocks.map((block, i) => {
        const key = `b${i}`;
        switch (block.kind) {
          case 'h2':
            return (
              <h3
                key={key}
                className="mb-2 font-[family-name:var(--font-display)] text-sm text-[color:var(--color-ink)]"
              >
                {block.text}
              </h3>
            );
          case 'h3':
            return (
              <div key={key} className="metric-label mt-4 mb-2 text-[color:var(--color-accent-2)]">
                {block.text}
              </div>
            );
          case 'quote':
            return (
              <p
                key={key}
                className="my-2 border-l-2 border-amber-400/50 bg-amber-500/5 py-1.5 pl-3 text-amber-100/90"
              >
                {inline(block.text, key)}
              </p>
            );
          case 'step': {
            stepNumber += 1;
            // A step is written `**Title** detail…`. Rendering it as one paragraph left the two
            // running together — bold in the DOM, but reading as a single sentence on screen.
            const titled = block.text.match(/^\*\*([^*]+)\*\*\s*(.*)$/s);
            return (
              <div key={key} className="mb-3 flex gap-2.5">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-[color:var(--color-accent)]/40 font-mono text-[10px] text-[color:var(--color-accent)]">
                  {stepNumber}
                </span>
                <div className="flex-1">
                  {titled ? (
                    <>
                      <div className="font-semibold text-[color:var(--color-ink)]">
                        {titled[1]}
                      </div>
                      {titled[2] && <p className="mt-0.5">{inline(titled[2], key)}</p>}
                    </>
                  ) : (
                    <p>{inline(block.text, key)}</p>
                  )}
                </div>
              </div>
            );
          }
          case 'bullet':
            return (
              <p key={key} className="mb-1 pl-3 text-[color:var(--color-ink-faint)]">
                — {inline(block.text, key)}
              </p>
            );
          case 'code':
            return (
              <pre
                key={key}
                className="my-2 ml-7 overflow-x-auto rounded border border-[color:var(--edge)] bg-black/50 p-2.5 font-mono text-[11px] text-[color:var(--color-safe)]"
              >
                {block.text}
              </pre>
            );
          default:
            return (
              <p key={key} className="mb-2">
                {inline(block.text, key)}
              </p>
            );
        }
      })}
      {modelSection && (
        <div className="mt-4 border-t border-[color:var(--edge)] pt-3">
          <pre className="whitespace-pre-wrap font-sans text-xs text-[color:var(--color-ink-faint)]">
            {modelSection.trim()}
          </pre>
        </div>
      )}
    </div>
  );
}
