"""Render a runnable harness that exercises the migrated primitive.

The harness imports **the patched file itself** and resolves the primitive class
from *that module's own namespace*. This is the whole design, and it is what makes
the stage a test of the patch rather than of the library:

* a patch that imported the wrong module fails here
* a patch that named a class the installed version does not have fails here
* a patch that asked for a parameter set that does not exist fails here
* a patch whose import is missing entirely fails here

and then the negative relations catch the case every earlier gate is blind to:
a rewrite that installed something which *accepts everything*.

What it deliberately does not do: exercise the application's own functions. Their
signatures are arbitrary and calling them with invented arguments would produce a
verdict about the harness, not the patch. The stated limit is that the relations
test the primitive **as the patched file imports and names it**, not the whole
protocol it sits inside.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from textwrap import indent

from .relations import RelationSet
from .shapes import PrimitiveShape, expected_size, shape_for

#: A primitive class as the patch refers to it — `mldsa.MLDSA65PrivateKey`, or a
#: bare `MLDSA65PrivateKey` when imported directly. Captured from the patched
#: source rather than assumed, because how the patch spells the name IS part of
#: what is being verified.
_QUALIFIED = r"(?:(?P<module>[A-Za-z_][\w.]*)\s*\.\s*)?(?P<cls>{name})"


@dataclass(frozen=True)
class HarnessPlan:
    """Everything needed to run the oracle, or the reason it cannot run."""

    source: str = ""
    #: The expression the harness will evaluate in the patched module's namespace.
    expression: str = ""
    family: str = ""
    #: Set when the oracle cannot run. The caller reports `skipped` with this,
    #: never `pass` — an oracle that did not run has established nothing.
    skip_reason: str = ""

    @property
    def runnable(self) -> bool:
        return bool(self.source) and not self.skip_reason


def _class_name(target_algorithm: str) -> str:
    """`ML-DSA-65` -> `MLDSA65PrivateKey`, matching how `cryptography` names them.

    Kept for the asymmetric families and for error messages. Symbol CHOICE now comes from the
    shape (see `candidate_symbols`), because `{compact}PrivateKey` describes a keypair and nothing
    else: AEAD is named `AESGCM` whatever the target string says, and a hash may be spelled
    `sha384` or `SHA384` depending on which library the patch reached for.
    """
    compact = target_algorithm.replace("-", "").replace("_", "").upper()
    return f"{compact}PrivateKey"


def candidate_symbols(shape: PrimitiveShape, target_algorithm: str) -> list[str]:
    """The names this patch might have used, most specific first.

    For a composite target the `{compact}` form is nonsense — `ML-DSA-65+ED25519` compacts to
    `MLDSA65+ED25519PrivateKey`, which is not a legal identifier and can never match. Only the
    component before the separator is kept, so a patch that named `MLDSA65PrivateKey` for the PQC
    half is still found.
    """
    head = target_algorithm.split("+")[0]
    compact = head.replace("-", "").replace("_", "").upper()
    return [s.replace("{compact}", compact) for s in shape.symbols]


def find_primitive_expression(
    patched_source: str,
    target_algorithm: str,
    shape: PrimitiveShape | None = None,
) -> str:
    """How the patched file refers to the target primitive, or "".

    Read out of the patch instead of constructed, so the harness exercises the name the patch
    actually wrote. A patch that wrote `mldsa65.MLDSA65PrivateKey` against a module that does not
    exist must fail, and it only can if the wrong spelling is carried through to here.

    Candidates are tried in the shape's declared order, most specific first, and the FIRST one
    present in the source wins. Order is load-bearing for hashes: `sha512` and `sha3_512` can both
    appear in a file that migrated two call sites, and matching the shorter one first would
    exercise the wrong primitive and report a verdict about a call the patch did not make.
    """
    names = candidate_symbols(shape, target_algorithm) if shape else [_class_name(target_algorithm)]
    for name in names:
        match = re.search(_QUALIFIED.format(name=re.escape(name)), patched_source)
        if match is None:
            continue
        module = match.group("module")
        # A dotted prefix can run back further than the reference — `a.b.MLDSAxx` is legitimate —
        # so the whole captured prefix is kept rather than its last part.
        return f"{module}.{name}" if module else name
    return ""


_TEMPLATE = '''\
"""Generated by qubit_migrate.oracles.harness — do not edit."""
import importlib.util
import json
import sys

MSG = b"qubit-oracle-probe-message"
MSG_TAMPERED = b"qubit-oracle-probe-messagX"

RESULTS = []


def record(rid, kind, outcome, detail=""):
    RESULTS.append({"id": rid, "kind": kind, "outcome": outcome, "detail": str(detail)[:400]})


def bail(reason):
    print(json.dumps({"status": "skipped", "reason": reason, "relations": RESULTS}))
    sys.exit(0)


try:
    spec = importlib.util.spec_from_file_location("qubit_patched", __MODULE_PATH__)
    patched = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(patched)
except BaseException as exc:
    # Not a verdict on the patch's cryptography: the file did not load at all,
    # which `compiles` already judges. Reported as skipped so one failure is not
    # counted twice under two different names.
    bail("patched module did not import: %s: %s" % (type(exc).__name__, exc))

namespace = dict(vars(patched))
try:
    KEY_CLASS = eval(__EXPR_REPR__, namespace)          # noqa: S307
except BaseException as exc:
    # THIS is a verdict. The patch named something that does not resolve in its
    # own import context — the exact failure `symbols` can miss when a name is
    # imported from a module that has no such attribute.
    print(json.dumps({
        "status": "fail",
        "reason": "the patch names __EXPR_REPR__, which does not resolve in its own module: %s: %s"
                  % (type(exc).__name__, exc),
        "relations": RESULTS,
    }))
    sys.exit(0)

try:
__SETUP__
except BaseException as exc:
    print(json.dumps({
        "status": "fail",
        # A construction failure is a verdict on the PATCH — the primitive it named cannot be
        # built the way its own family is built — but it is reported distinctly from a relation
        # failure, because "the primitive misbehaved" and "the primitive could not be made" are
        # different findings and a repair loop needs different feedback for each.
        "reason": "could not construct the primitive from __EXPR_REPR__: %s: %s"
                  % (type(exc).__name__, exc),
        "relations": RESULTS,
    }))
    sys.exit(0)

__BODY__

failed = [r for r in RESULTS if r["outcome"] == "fail"]
print(json.dumps({
    "status": "fail" if failed else "pass",
    "reason": "; ".join("%s: %s" % (r["id"], r["detail"]) for r in failed),
    "relations": RESULTS,
}))
'''

_POSITIVE_BLOCK = """
# {rid} ({kind}) — {relation}
try:
    result = None
    {fragment}
    if result is False:
        record({rid!r}, {kind!r}, "fail", "the relation evaluated False")
    else:
        record({rid!r}, {kind!r}, "pass", "")
except BaseException as exc:
    record({rid!r}, {kind!r}, "fail", "%s: %s" % (type(exc).__name__, exc))
"""

_NEGATIVE_BLOCK = """
# {rid} ({kind}) — {relation}
# A negative relation passes when the primitive REJECTED the input. Rejection is
# an exception for signatures (verify raises rather than returning False) and an
# inequality for ML-KEM (implicit rejection returns a different secret, and only
# a wrong-LENGTH ciphertext raises) — so both count.
try:
    result = None
    {fragment}
    if result is True:
        record({rid!r}, {kind!r}, "pass", "rejected by inequality")
    elif result is None:
        record({rid!r}, {kind!r}, "fail",
               "accepted input it must reject — no exception, no inequality")
    else:
        record({rid!r}, {kind!r}, "fail", "accepted input it must reject")
except BaseException as exc:
    record({rid!r}, {kind!r}, "pass", "rejected with %s" % type(exc).__name__)
"""

_ADVISORY_BLOCK = """
# {rid} ({kind}, advisory — reported, never fails the stage) — {relation}
try:
    measured = {fragment}
    floor = {floor!r}
    if floor is not None and measured < floor:
        record({rid!r}, {kind!r}, "advisory",
               "measured %s, expected at least %s — the classical path may still be live"
               % (measured, floor))
    else:
        record({rid!r}, {kind!r}, "advisory", "measured %s" % (measured,))
except BaseException as exc:
    record({rid!r}, {kind!r}, "advisory", "not measurable: %s" % type(exc).__name__)
"""


#: Sizes a fragment may ask for, and the `EXPECTED_SIZES` key each maps to.
_SIZE_PLACEHOLDERS = {
    "__EXPECTED_DIGEST__": "digest",
    "__EXPECTED_EXPANSION__": "expansion",
    "__EXPECTED_SIGNATURE__": "signature_min",
    "__EXPECTED_SECRET__": "secret",
}


def _fill_sizes(fragment: str, target_algorithm: str) -> str | None:
    """Substitute probed sizes into a fragment, or None if one is unknown.

    Explicit placeholders rather than `str.format`, for the same reason the template uses them:
    the fragments are full of dict literals and slice syntax, and doubling every brace is a bug
    farm that already produced a `KeyError: '"id"'`.
    """
    for placeholder, key in _SIZE_PLACEHOLDERS.items():
        if placeholder not in fragment:
            continue
        size = expected_size(target_algorithm, key)
        if size is None:
            return None
        fragment = fragment.replace(placeholder, str(size))
    return fragment


def build(
    relation_set: RelationSet,
    patched_source: str,
    target_algorithm: str,
    module_path: str = "/work/patched.py",
) -> HarnessPlan:
    """Render the harness, or explain why the oracle cannot run.

    Every refusal path returns a `skip_reason` rather than an empty pass. An
    oracle that did not run has established nothing, and recording that as
    success is the exact failure the admission controls exist to catch.
    """
    if not relation_set:
        return HarnessPlan(skip_reason="no metamorphic relations cover this usage context")
    if not relation_set.can_award_evidence:
        return HarnessPlan(
            skip_reason=(
                f"the {relation_set.family} relation family has no negative relation, so it "
                "cannot distinguish a working primitive from one that accepts everything"
            )
        )

    shape: PrimitiveShape | None = shape_for(target_algorithm)
    if shape is None:
        return HarnessPlan(
            skip_reason=f"no probed API shape for {target_algorithm!r}",
            family=relation_set.family,
        )

    expression = find_primitive_expression(patched_source, target_algorithm, shape)
    if not expression:
        return HarnessPlan(
            skip_reason=(
                "the patch references none of "
                f"{candidate_symbols(shape, target_algorithm)}, so there is no primitive "
                "to exercise"
            ),
            family=relation_set.family,
        )

    blocks: list[str] = []
    for relation in relation_set.relations:
        fragment = shape.ops.get(relation.id)
        if fragment is None:
            # A relation with no probed fragment is silently skipped rather than
            # guessed. It simply does not contribute evidence.
            continue
        fragment = _fill_sizes(fragment, target_algorithm)
        if fragment is None:
            # The fragment needs a size this target has no probed value for. Dropping it is the
            # only honest option: substituting a permissive default would leave a relation that
            # runs, reports `pass`, and cannot fail — which is worse than one that never ran,
            # because it looks like evidence.
            continue
        if relation.advisory:
            floor = expected_size(target_algorithm, "signature_min") or expected_size(
                target_algorithm, "secret"
            )
            blocks.append(
                _ADVISORY_BLOCK.format(
                    rid=relation.id,
                    kind=relation.kind,
                    relation=relation.relation,
                    fragment=fragment,
                    floor=floor,
                )
            )
        elif relation.kind == "negative":
            blocks.append(
                _NEGATIVE_BLOCK.format(
                    rid=relation.id,
                    kind=relation.kind,
                    relation=relation.relation,
                    fragment=fragment,
                )
            )
        else:
            blocks.append(
                _POSITIVE_BLOCK.format(
                    rid=relation.id,
                    kind=relation.kind,
                    relation=relation.relation,
                    fragment=fragment,
                )
            )

    if not any("negative" in b for b in blocks):
        return HarnessPlan(
            skip_reason=(
                "no negative relation had a probed fragment, so the harness could not tell a "
                "working primitive from one that accepts everything"
            ),
            family=relation_set.family,
        )

    # Explicit placeholders rather than `str.format`: the generated source is full
    # of dict literals and %-format braces, and doubling every one of them is a bug
    # farm that already produced a `KeyError: '"id"'` on the `record()` body.
    source = (
        _TEMPLATE.replace("__MODULE_PATH__", repr(module_path))
        .replace("__EXPR_REPR__", repr(expression))
        # Indented into the `try:` that guards construction. `textwrap.indent` rather than a
        # per-line join, so a blank line inside a multi-line setup does not acquire trailing
        # whitespace and trip the generated file's own lint.
        .replace("__SETUP__", indent(shape.setup, "    "))
        .replace("__BODY__", "\n".join(blocks))
    )
    return HarnessPlan(source=source, expression=expression, family=relation_set.family)
